--DB: ammdb ; user: silvia_frau ; pass: amm;

CREATE TABLE postType (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE utenti (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256),
	cognome VARCHAR(256),
    email VARCHAR(256),
	username VARCHAR(256)UNIQUE,
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256),
	presentazione VARCHAR(256)
);

CREATE TABLE posts (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
	url VARCHAR(1024),
	image VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(id)
);

CREATE TABLE gruppi(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(256),
	numUtenti INTEGER,
	utente INTEGER, FOREIGN KEY(utente) REFERENCES utenti (id)
);

--Popolamento tabella utenti
INSERT INTO utenti (id, name,cognome, email, username, password, urlFotoProfilo, presentazione)
VALUES (default,
        'Gigi',
		'Palla',
        'Pallino@gmail.com',
        'Gigino',
        '123',
        'FotoProfilo.jpg'
		'Ciao raga, sono un fotomodelo al gusto di nutelo!!!');
		

INSERT INTO utenti (id, name,cognome, email, username, password, urlFotoProfilo, presentazione)
VALUES (default,
        'Tonio',
		'Cartonio',
        'BALORDO@gmail.com',
		'Tonnio',
        'miao',
        'img.jpg',
		'Aggiusto computer for free, se mi volete contattare ;) ');

INSERT INTO utenti(id, name,cognome, email, username, password, urlFotoProfilo, presentazione)
VALUES (default,
        'Anna',
		'Pannocchia',
        'SonoIncintaMarioo@gmail.com',
		'Pannocchietta99',
        '123',
        'gat.jpg',
		'Mariotiamoooooo');
		
		
INSERT INTO utenti(id, name,cognome, email, username, password, urlFotoProfilo, presentazione)
VALUES (default,
        'Mario',
		'',
        'Hofame@gmail.com',
		'Mariottide',
        'biscotto',
        '',
		'');



		
		--Popolamento tabella PostType
INSERT INTO posttype (id, name)
VALUES (default, 'TEXT');

INSERT INTO posttype (id, name)
VALUES (default, 'IMAGE');

INSERT INTO posttype (id, name)
VALUES (default, 'URL');

--Popolamento tabella Post
INSERT INTO posts (id, content, url, image, type, author)
VALUES (default,
        'Giovane di modesta prestanza fisica e dall aspetto insignificante, che compensa la scarsa avvenenza e le frustrazioni che ne derivano con una passione ossessiva e una notevole inclinazione per le nuove tecnologie',
        '',
		'',
		1,
        0);

INSERT INTO posts (id, content, url, image, type, author)
VALUES (default,
        'Non vedo l ora di giocare a tekken!!!!!!!',
        '',
		'download.jpg',
		2,
        1);

INSERT INTO posts (id, content, url, image, type, author)
VALUES (default,
        'Gattini coccolini. Guardateeeee!!!',
        'https://www.google.it/search?q=nerd&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiczNDu2OTSAhXCvxQKHanjDjwQ_AUICCgB&biw=1366&bih=662#tbm=isch&q=gattini&*&imgrc=LKZjnAkGIJpnpM:',
		'',
		3,
        2);

INSERT INTO posts (id, content, url, image, type, author)
VALUES (default,
        'Oggi fa proprio caldo per stare in giro :( ',
        '',
		'',
		0,
        2);

INSERT INTO gruppi(id, nome)
VALUES (default,
		'Mariogattini');

INSERT INTO gruppi(id, nome)
VALUES (default,
		'Supernatural');	

INSERT INTO gruppi(id, nome)
VALUES (default,
		'GymWirkOut');			

INSERT INTO gruppi(id, nome)
VALUES (default,
		'ChaoPovery');			
