--DB: ammdb ; user: silvia_frau ; pass: amm;

CREATE TABLE postType (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE utenti (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE,
    email VARCHAR(256),
	username VARCHAR(256);
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256)
);

CREATE TABLE posts (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(id)
);

CREATE TABLE gruppi(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(256),
	numUtenti INTEGER,
	utente INTEGER, FOREIGN KEY(utente) REFERENCES utenti (id)
);

--Popolamento tabella utenti
INSERT INTO utenti (id, name, email, username, password, urlFotoProfilo)
VALUES (default,
        'Gigi Palla',
        'GigiPalla@gmail.com',
        'Incrocio',
        '123',
        'img/djanniprofilo.jpg');

INSERT INTO utenti (id, name, email, username, password, urlfotoprofilo)
VALUES (default,
        'Tonio Cartonio',
        'Tonnnio@gmail.com',
        'British Shorthair',
        '123',
        'img/user1.gif');

INSERT INTO utenti(id, name, email, username, password, urlfotoprofilo)
VALUES (default,
        'Anna Pannocchia',
        'Marioloveu@gmail.com',
        'Gatto Sacro di Birmania',
        '123',
        'img/user2.jpg');



		
		--Popolamento tabella PostType
INSERT INTO posttype (id, name)
VALUES (default, 'TEXT');

INSERT INTO posttype (id, name)
VALUES (default, 'IMAGE');

--Popolamento tabella Post
INSERT INTO posts (id, content, type, author)
VALUES (default,
        'Ciao, miei schiavi. Datemi cibo! Adesso! Miaomiaomiaomiaomiao!',
        1,
        1);

INSERT INTO posts (id, content, type, author)
VALUES (default,
        'img/djanni1.jpg',
        2,
        1);

INSERT INTO posts (id, content, type, author)
VALUES (default,
        'img/djanni2.jpg',
        2,
        1);

INSERT INTO posts (id, content, type, author)
VALUES (default,
        'I need ansioliticy',
        1,
        2);

INSERT INTO posts (id, content, type, author)
VALUES (default,
        'https://68.media.tumblr.com/51942e1f788f7209ee0f6db7cfc5e0fb/tumblr_n37ycpbMZf1rkxod7o1_500.jpg',
        2,
        2);
